Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/week7/go2_walk_pth/go2_stand (1).py", line 93, in <module>
    envs = AsyncVectorEnv([make_env() for _ in range(NUM_ENVS)])
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/gymnasium/vector/async_vector_env.py", line 156, in __init__
    dummy_env = env_fns[0]()
  File "/Users/advaitdesai/Programming/eklavya/week7/go2_walk_pth/go2_stand (1).py", line 75, in _init
    return gym.make(
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/gymnasium/envs/registration.py", line 734, in make
    env = env_creator(**env_spec_kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/gymnasium/envs/mujoco/ant_v5.py", line 285, in __init__
    MujocoEnv.__init__(
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/gymnasium/envs/mujoco/mujoco_env.py", line 72, in __init__
    self.fullpath = expand_model_path(model_path)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/gymnasium/envs/mujoco/mujoco_env.py", line 31, in expand_model_path
    raise OSError(f"File {fullpath} does not exist")
OSError: File ./unitree_go2/scene.xml does not exist
